import React from 'react';
import {
  AcademicCapIcon,
  BellIcon,
  BookOpenIcon,
  BookmarkIcon,
  BriefcaseIcon,
  BuildingOfficeIcon,
  CalendarIcon,
  CheckCircleIcon,
  ClipboardListIcon,
  ClockIcon,
  CollectionIcon,
  DesktopComputerIcon,
  DocumentSearchIcon,
  DocumentTextIcon,
  FlaskIcon,
  GridIcon,
  HomeIcon,
  IdentificationIcon,
  LibraryIcon,
  LinkIcon,
  MapIcon,
  NetworkIcon,
  PresentationChartBarIcon,
  ShieldCheckIcon,
  SlidersIcon,
  SparklesIcon,
  TableCellsIcon,
  UserGroupIcon,
  UserTieIcon,
  VideoCameraIcon,
  WifiIcon,
} from './icons';

export const iconMap: { [key: string]: React.FC<React.SVGProps<SVGSVGElement>> } = {
  AcademicCapIcon,
  BellIcon,
  BookOpenIcon,
  VideoCameraIcon,
  BriefcaseIcon,
  BuildingOfficeIcon,
  CalendarIcon,
  CheckCircleIcon,
  ClipboardListIcon,
  ClockIcon,
  CollectionIcon,
  DesktopComputerIcon,
  DocumentSearchIcon,
  DocumentTextIcon,
  FlaskIcon,
  GridIcon,
  HomeIcon,
  IdentificationIcon,
  LibraryIcon,
  LinkIcon,
  MapIcon,
  NetworkIcon,
  PresentationChartBarIcon,
  ShieldCheckIcon,
  SlidersIcon,
  SparklesIcon,
  TableCellsIcon,
  UserGroupIcon,
  UserTieIcon,
  WifiIcon,
  BookmarkIcon,
};

export const iconNames = Object.keys(iconMap);

export const iconLabels: Record<string, string> = {
  AcademicCapIcon: 'Обучение',
  BellIcon: 'Звонки',
  BookOpenIcon: 'Книга',
  BookmarkIcon: 'Закладка',
  BriefcaseIcon: 'Кафедра',
  BuildingOfficeIcon: 'Корпус',
  CalendarIcon: 'Календарь',
  CheckCircleIcon: 'Готово',
  ClipboardListIcon: 'Список',
  ClockIcon: 'Время',
  CollectionIcon: 'Коллекция',
  DesktopComputerIcon: 'Компьютер',
  DocumentSearchIcon: 'Поиск',
  DocumentTextIcon: 'Документ',
  FlaskIcon: 'Лаборатория',
  GridIcon: 'Сетка',
  HomeIcon: 'Помещение',
  IdentificationIcon: 'Код',
  LibraryIcon: 'Библиотека',
  LinkIcon: 'Связь',
  MapIcon: 'План',
  NetworkIcon: 'Привязки',
  PresentationChartBarIcon: 'Презентация',
  ShieldCheckIcon: 'Правила',
  SlidersIcon: 'Настройки',
  SparklesIcon: 'Авто',
  TableCellsIcon: 'Таблица',
  UserGroupIcon: 'Группа',
  UserTieIcon: 'Преподаватель',
  VideoCameraIcon: 'Видео',
  WifiIcon: 'Онлайн',
};

export const renderIcon = (iconName: string | undefined, props: React.SVGProps<SVGSVGElement> = {}) => {
  if (!iconName) return null;
  const IconComponent = iconMap[iconName];
  return IconComponent ? <IconComponent {...props} /> : <BookmarkIcon {...props} />;
};
